config/routes.rb
ReporterApp::Application.routes.draw do
  
  root :to => 'home_pages#welcome'
  devise_for :users
  resources :users
  match 'home_pages/summary' => 'home_pages#summary', :as => :summary
  match 'home_pages/details' => 'home_pages#details', :as => :details
  
  namespace :admin do
    root :to => 'home_pages#index'
    resources :users
    resources :accounts
    resources :applications
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :applications, :dependent => :destroy
  
  validates :username, :password, :vendorid, :presence => true
  
  accepts_nested_attributes_for :applications,
                                 :reject_if => lambda{ |application| application[:name].blank? || application[:apple_identifier].blank? },
                                 :allow_destroy => true
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
    redirect_to [:admin, @account], notice: 'Account was successfully created.'
    else
    render action: "new"
    end
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      redirect_to [:admin, @account], notice: 'Account was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to admin_accounts_url
  end
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/admin/accounts/_form.html.erb
<%= form_for [:admin, @account], :html => {:class => 'nice'} do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.label :username %>
	<%= f.text_field :username, :class => 'input-text' %>
	<%= f.label :password %>
	<%= f.password_field :password, :class => 'input-text' %>
	<%= f.label :vendorid %>
	<%= f.text_field :vendorid, :class => 'input-text' %>
	<%= f.submit :class => "button blue small radius" %>
<% end %>

app/views/admin/accounts/edit.html.erb
<h3>Editar cuenta</h3>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @account] %> |
<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/index.html.erb
<h3>Cuentas</h3>

<table>
	<thead>
  	<tr>
		  <th>Username</th>
	    <th>Password</th>
	    <th>Vendor Id</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	<% @accounts.each do |account| %>
	  <tr>
		  <td><%= account.username %></td>
	    <td><%= account.password %></td>
	    <td><%= account.vendorid %></td>
	    <td><%= link_to 'Ver', [:admin, account] %></td>
	    <td><%= link_to 'Editar', edit_admin_account_path(account) %></td>
	    <td><%= link_to 'Eliminar', [:admin, account], confirm: 'Estas seguro?', method: :delete %></td>
	  </tr>
	<% end %>
	</tbody>
</table>

<br />

<%= link_to 'Nueva Cuenta', new_admin_account_path, :class => "button blue small radius" %>

app/views/admin/accounts/new.html.erb
<h3>Nueva cuenta</h3>

<%= render 'form' %>

<%= link_to 'Atras', admin_accounts_path %>

app/views/admin/accounts/show.html.erb
<p>
	<b>Username:</b>
	<%= @account.username %>
</p>

<p>
	<b>Password:</b>
	<%= @account.password %>
</p>

<p>
	<b>Vendor Id:</b>
	<%= @account.vendorid %>
</p>

<%= link_to 'Editar', edit_admin_account_path(@account) %> |
<%= link_to 'Atras', admin_accounts_path %>