config/routes.rb
ReporterApp::Application.routes.draw do
  
  root :to => 'home_pages#welcome'
  devise_for :users
  resources :users
  match 'home_pages/summary' => 'home_pages#summary', :as => :summary
  match 'home_pages/details' => 'home_pages#details', :as => :details
  
  namespace :admin do
    root :to => 'home_pages#index'
    resources :users
    resources :accounts
    resources :applications
  end

end

app/controllers/admin/home_pages_controller.rb
class Admin::HomePagesController < Admin::BaseController
  def index
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
    
  before_filter :authenticate_user!, :except => :welcome
  
  def welcome
    if current_user
      redirect_to summary_url
    else
      render :layout => false
    end
  end  
    
  def summary
    get_parameters_summary
    @dates_from_14_days = get_days
    @dates_from_14_weeks = get_weeks
    @downloads = Statistics.downloads(current_user, @type_query, @date)
    @purchases = Statistics.purchases(current_user, @type_query, @date)
    @updates = Statistics.updates(current_user, @type_query, @date)
  end
  
  def details
    get_parameters_details
    @dates_from_14_days = get_days
    @dates_from_14_weeks = get_weeks
    @applications = Statistics.get_all_statistics(current_user, @type_query, @date)
  end
  
  def get_days
    days = []
    14.times do |i|
      value = (yesterday- i.day).strftime("%Y%m%d")
      display = (yesterday - i.day).strftime("%d/%m/%Y")
      days << [display, value]
    end
    days
  end
  
  def get_weeks
    weeks = []
    14.times do |i|
      value = (yesterday - i.week).strftime("%Y%m%d")
      display = (yesterday- i.week).strftime("%d/%m/%Y")
      weeks << [display, value]
    end
    weeks
  end
  
  def get_parameters_details
    if !initial_request?
      @type_query = 'weekly'
      @date = yesterday.strftime("%Y%m%d")
    else
      @type_query = params[:type_query]
      @date = params[:start_date]
    end
    cookies[:tab_active] = @type_query
  end
  
  def get_parameters_summary
    if !initial_request?
      @type_query = 'dayly'
      @date = yesterday.strftime("%Y%m%d")
    else
      @type_query = params[:type_query]
      @date = params[:start_date]
    end
    cookies[:tab_active] = @type_query
  end
  
  def initial_request?
    params[:type_query] && params[:start_date] 
  end
  
  def yesterday
    Time.now - 1.day
  end
  
end

app/views/home_pages/_details_fields.html.erb
<% @applications.each do |application|%>
<div class="application">
  <b>Application:</b>
		<%= application.title %>
	</p>
	<p>
		<b>Developer:</b>
		<%= application.developer %>
	</p>
	<p>
	<p>
		<b>Version:</b>
		<%= application.version %>
	</p>

	<p>
		<b>Provider Country:</b>
		<%= humanize_country_code(application.provider_country) %>
	</p>

	<p>
		<b>Begin Date:</b>
		<%= application.begin_date %>
	</p>

	<p>
		<b>End Date:</b>
		<%= application.end_date %>
	</p>

	<p>
		<b>Product Type:</b>
		<%= humanize_product_type_identifier(application.product_type_identifier) %>
	</p>

	<p>
		<b>Units:</b>
		<%= application.units %>
	</p>

	<p>
		<b>Customer Currency:</b>
		<%= humanize_customer_currency(application.customer_currency) %>
	</p>
</div>
<% end %>

app/views/home_pages/_summary_fields.html.erb
<p>
  <b>Downloads:</b>
  <%= @downloads %>
</p>
<p>
  <b>Updates:</b>
  <%= @updates %>
</p>
<p>
  <b>Purchases:</b>
  <%= @purchases %>
</p>

app/views/home_pages/details.html.erb
<h3>Details</h3>

<dl class="nice contained tabs">
  <dd><a href="#dayly"  class="<%= if cookies[:tab_active] == 'dayly' then 'active' end %>">Dayly</a></dd>
  <dd><a href="#weekly" class="<%= if cookies[:tab_active] == 'weekly' then 'active' end %>">Weekly</a></dd>
</dl>

<ul class="nice tabs-content contained">
  <li class="<%= if cookies[:tab_active] == 'dayly' then 'active' end %>" id="daylyTab">
    <%= form_tag details_path, :id => "consult" do %>
      <%= hidden_field_tag(:type_query, "dayly") %>
      <%= select_tag :start_date, options_for_select(@dates_from_14_days) %>
      <%= submit_tag "Buscar" %>
    <% end %>
    <%= render 'details_fields' %>
  </li>
  <li class="<%= if cookies[:tab_active] == 'weekly' then 'active' end %>" id="weeklyTab">
    <%= form_tag details_path, :id => "consult" do %>
      <%= hidden_field_tag(:type_query, "weekly") %>
      <%= select_tag :start_date, options_for_select(@dates_from_14_days) %>
      <%= submit_tag "Buscar" %>
    <% end %>
    <%= render 'details_fields' %>
  </li>
</ul>

app/views/home_pages/summary.html.erb
<h3>Summary</h3>

<dl class="nice contained tabs">
  <dd><a href="#dayly"  class="<%= if cookies[:tab_active] == 'dayly' then 'active' end %>">Dayly</a></dd>
  <dd><a href="#weekly" class="<%= if cookies[:tab_active] == 'weekly' then 'active' end %>">Weekly</a></dd>
</dl>

<ul class="nice tabs-content contained">
  <li class="<%= if cookies[:tab_active] == 'dayly' then 'active' end %>" id="daylyTab">
    <%= form_tag summary_path, :id => "consult" do %>
      <%= hidden_field_tag(:type_query, "dayly") %>
      <%= select_tag :start_date, options_for_select(@dates_from_14_days) %>
      <%= submit_tag "Buscar" %>
    <% end %>
    <%= render 'summary_fields' %>
  </li>
  <li class="<%= if cookies[:tab_active] == 'weekly' then 'active' end %>" id="weeklyTab">
    <%= form_tag summary_path, :id => "consult" do %>
      <%= hidden_field_tag(:type_query, "weekly") %>
      <%= select_tag :start_date, options_for_select(@dates_from_14_days) %>
      <%= submit_tag "Buscar" %>
    <% end %>
    <%= render 'summary_fields' %>
  </li>
</ul>

app/views/home_pages/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script type="text/javascript">
	     $(window).load(function() {
	         $('#featured').orbit();
	     });
	</script>
</head>
<body class="container">
			<header class="row">
				<div class="seven columns">
					<h2>ReporterApp</h2>
					<p>Estadisticas de tus aplicaciones Apple</p>
					<hr />
				</div>
				<div class="five columns">
					<div class="row">
						<div class="twelve columns">
						  <%= form_for :user, :url => user_session_path, :html => {:class => "nice login"} do |f| %>
                <%= f.text_field :email, :class => "input-text small" %>
                <%= f.password_field :password, :class => "input-text small" %>
                <%= f.submit 'Entra', :class => "button blue small radius inlined" %><br/>
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
                <!--<%= link_to "Olvidaste tu contraseña?", new_password_path('user') %>-->
              <% end %>
						</div>
					</div>
					<div class="row">
						<div class="twelve columns offset-by-eight">
							<%= image_tag "facebook.png", :alt => "facebook" %>
							<%= image_tag "twitter.png", :alt => "twitter" %>
						</div>
					</div>
				</div>
			</header>
		
		  <div class="row">
		  	<div class="eight columns">
						<div id="featured">
							<%= image_tag "foto1.jpg", :alt => "foto1" %>
							<%= image_tag "foto2.jpg", :alt => "foto2" %>
							<%= image_tag "foto3.jpg", :alt => "foto3" %>
						</div>
				</div>
				<div class="four columns">
					<%= form_for :user, :url => user_registration_path, :html => {:class => "nice"} do |f| %>
					<%= f.label :email %>
					<%= f.text_field :email, :class => "input-text" %>
					<%= f.label :password %>
					<%= f.password_field :password, :class => "input-text" %>
					<%= f.label :password_confirmation %>
					<%= f.password_field :password_confirmation, :class => "input-text" %>

					<%= f.submit "Registrarme", :class => "button blue small radius" %></p>
					<% end %>
				</div>
			</div>
			
			<div class="row">
				
				<div class="four columns">
					<h5>Las Mejores estadisticas</h5>
					<p>Usuario ha entregado el siguiente objeto.</p>
					<p>
						Lorem ipsum dolor sit amet.<br/>
						Phasellus venenatis semper.
					</p>
				</div>
				
				<div class="four columns">
					<h5>Informes a medida</h5>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
						Donec nisl nibh, pretium non dignissim vitae, feugiat vitae dolor. Mauris in sollicitudin nisl.
						Phasellus venenatis semper congue. 
					<p/>
				</div>
				
				<div class="four columns">
					<h5>Gráficas dinamica</h5>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
						Donec nisl nibh, pretium non dignissim vitae, feugiat vitae dolor. Mauris in sollicitudin nisl.
						Phasellus venenatis semper congue. 
					<p/>
				</div>
				
			</div>

			<footer class="row">			
				<div class="four columns">
					Footer
				</div>
			</footer>
</body>
</html>