config/routes.rb
ReporterApp::Application.routes.draw do
  
  root :to => 'home_pages#welcome'
  devise_for :users
  resources :users
  match 'home_pages/summary' => 'home_pages#summary', :as => :summary
  match 'home_pages/details' => 'home_pages#details', :as => :details
  
  namespace :admin do
    root :to => 'home_pages#index'
    resources :users
    resources :accounts
    resources :applications
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :accounts_attributes
  
  has_many :accounts, :dependent => :destroy
  
  accepts_nested_attributes_for :accounts,
                                :reject_if => lambda{ |account| account[:username].blank? || account[:password].blank? || account[:vendorid].blank?},
                                :allow_destroy => true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new 
    @user = User.new
    1.times do
      accounts = @user.accounts.build
      1.times { accounts.applications. build }
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to [:admin, @user], :notice => "El usuario fue creado correctamente."
    else
      render :action => 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to [:admin, @user], :noitce => "El usuario fue actualizado correctamente."
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(parms[:id])
    @user.destroy
    redirecto_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to edit_user_url(@user), :noitce => "El usuario fue actualizado correctamente."
    else
      render :action => 'edit'
    end
  end
end

app/views/admin/users/_account_fields.html.erb
<fieldset>
	<h5>Nueva Cuenta IT</h5>
	<%= builder.label :username %>
	<%= builder.text_field :username, :class => 'input-text' %>
	<%= builder.label :password %>
	<%= builder.password_field :password, :class => 'input-text' %>
	<%= builder.label :vendorid %>
	<%= builder.text_field :vendorid, :class => 'input-text' %>
	<%= builder.hidden_field :_destroy %>
	<%= link_to_remove_fields "Eliminar", builder %>
	
	<%= builder.fields_for :applications do |builder| %>
		<%= render 'application_fields', :builder => builder%>
	<% end %>
	
	<p><%= link_to_add_fields "Añadir Aplicación", builder, :applications %></p>
</fieldset>

app/views/admin/users/_application_fields.html.erb
<fieldset class="application">
	<h5>Nueva Applicación</h5>
	<%= builder.label :name %>
	<%= builder.text_field :name, :class => 'input-text' %>
	<%= builder.label :apple_identifier %>
	<%= builder.text_field :apple_identifier, :class => 'input-text' %>
	<%= builder.hidden_field :_destroy %>
	<%= link_to_remove_fields "Eliminar", builder %>
</fieldset>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :html => {:class => 'nice'} do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this admin_application from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<%= f.label :email %>
	<%= f.text_field :email, :class => 'input-text' %>
	<%= f.label :password %>
	<%= f.password_field :password, :class => 'input-text' %>
	
	
	<%= f.fields_for :accounts do |builder| %>
		<%= render 'account_fields', :builder => builder%>
	<% end %>
	
	<p><%= link_to_add_fields "Añadir Cuenta", f, :accounts %></p>
	
	<%= f.submit :class => "button blue small radius" %>
<% end %>

app/views/admin/users/edit.html.erb
<h3>Editar usuairo</h3>

<%= render 'form' %>

<%= link_to 'Ver', [:admin, @user] %>
<%= link_to 'Atras', admin_users_path %>

app/views/admin/users/index.html.erb
<h3>Usuarios<h3>
	
<table>
	<thead>
		<tr>
			<th>Email</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td><%= link_to 'Ver', [:admin, user] %></td>
				<td><%= link_to 'Editar', edit_admin_user_path(user) %></td>
				<td><%= link_to 'Eliminar', [:admin, user], :confirm => 'Estas seguro?', :method => :delete %></td>		
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'Nuevo usuario', new_admin_user_path, :class => "button blue small radius" %>

app/views/admin/users/new.html.erb
<h3>Nuevo usuario</h3>

<%= render 'form' %>

<%= link_to 'Atras', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
	<b>Email:</b>
	<%= @user.email %>
</p>

<h5>Cuentas IT</h5>
<% @user.accounts.each do |account| %>
<div style="background:#EEE">
	<p>
		<b>Vendor ID:</b>
		<%= account.vendorid %>
	</p>
	<p>
		<b>Username:</b>
		<%= account.username %>
	</p>
	<h6>Aplicaciones</h6>
	<ol>
		<% account.applications.each do |application| %>
			<li><%= application.name %></li>
		<% end %>
	</ol>
</div>		
<% end %>

<%= link_to 'Editar', edit_admin_user_path(@user) %>
<%= link_to 'Atras', admin_users_path %>