config/routes.rb
ReporterApp::Application.routes.draw do
  
  root :to => 'home_pages#welcome'
  devise_for :users
  resources :users
  match 'home_pages/summary' => 'home_pages#summary', :as => :summary
  match 'home_pages/details' => 'home_pages#details', :as => :details
  
  namespace :admin do
    root :to => 'home_pages#index'
    resources :users
    resources :accounts
    resources :applications
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ReporterApp - Administrator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
	<div class="row">
		<div class="two columns">
			<dl class="nice vertical tabs">
			  <dd><%= link_to "Usuarios", admin_users_path %></dd>
			  <dd><%= link_to "Cuentas IT", admin_accounts_path %></dd>
			  <dd><%= link_to "Applicaciones", admin_applications_path %></dd>
			</dl>
		</div>
		<div class="ten columns">
			<%= messages_about_actions %>
			<%= yield %>
		</div>
	</div>
</body>
<html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ReporterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
	<div class="row">
		<div class="two columns">
			<dl class="nice vertical tabs">
			  <dd><%= link_to "Summary", summary_path %></dd>
			  <dd><%= link_to "Details", details_path %></dd>
			  <dd><%= link_to "Perfil Cuentas", edit_user_path(current_user) %></dd>
			   <dd> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </dd>
			</dl>
		</div>
		<div class="ten columns">
			<%= messages_about_actions %>
			<%= yield %>
		</div>
	</div>
</body>
<html>